# Site settings
title: Tomohiro Matsuo
description: Web Engineer & Photographer
keywords: Tomohiro, Matsuo
author: Tomohiro Matsuo
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
