version: "3"
services:
  service_jekyll:
    image: jekyll/jekyll:3.8.6
    container_name: local_jekyll
    working_dir: /app
    volumes:
      - .:/app
    command: jekyll serve -s /app --watch --verbose --trace
    ports:
      - "4000:4000"
